# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee5f63b3a4821cd5fa470fd533a4b3da276604fe7b4708719282ce0bb8ed3af43df0a1666eac41089c0b4b12eaec8e24ccb320923f88832dcc5fdf0d41a58691

test:
  secret_key_base: 0cf8e673dc11c01c9fd7c4485a3437473499ccde597be96dd56236d5b496491dacb6fc1e09859e6f663d1efdcc55626b32d5cf74752a35e064509c14d83c5cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
